App_Main/urls.py
from django.urls import path
from .views import *
app_name='App_Main'

urlpatterns = [
    path('', Main_Home, name = 'home'),
    path('pet/info',Pet_info_View, name = 'pet'),  
    path('pet/info/create', Pet_create_View, name = 'pet_create'),
    path('pet/info/update', Pet_update_View, name  = 'pet_update'),
    path('pet/statistics', Pet_statistics_View, name = 'pet_statistics'),
    path('pet/diet/info', Pet_info_View, name = 'pet_diet_info'),
    path('pet/diet/set', Pet_diet_set_View, name = 'pet_diet_set'),
    path('pet/diet/update', Pet_diet_set_View, name = 'pet_diet_update'),
]


config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views as TokenViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Main.urls')),
    path('auth/', include('App_User.urls')),
    path('wsc/', include('App_WSC.urls')),
    path('api/', include('App_API.urls')),
    path("api/auth", TokenViews.obtain_auth_token, name="obtain_auth_token"),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


App_Main/models.py
from django.db import models
from App_User.models import User

pet_status_choices = [
    ('성견__중성화', "Adult_Neutering"),
    ('성견__미중성화', 'Adult_NonNeutering'),
    ('성견__비만경향', 'Adult_Obese_NonActive'),
    ('성견__활동적', 'Adult_Active'),
    ('성견__매우 활동적', 'Adult_Very_Active'),
    ('성견__체중감량', 'Adult_Wloss'),
    ('성견__체중증가', 'Adult_gain'),
    ('성견__아픔', 'Adult_Week'),
    ('성장기__생후 4개월 전', 'Growth_Ud4'),
    ('성장기__4개월 이후 ~ 성견 전', 'Growth_Up4'),
    ('임신 전반 6주', 'Pregent_6W'),
    ('임신 전반 3주', 'Pregent_3W'),
    ('수유 1마리', 'Nursing_1'),
    ('수유 2마리', 'Nursing_2'),
    ('수유 3~4마리', 'Nursing_3_4'),
    ('수유 5~6마리', 'Nursing_5_6'),
    ('수유 7~8마리', 'Nursing_7_8'),
    ('수유 9마리 이상', 'Nursing_9')
]

class Pet_info(models.Model):
    pet_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    pet_name = models.CharField(max_length = 100)
    pet_birth = models.DateField(null = True, blank = True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        # 객체를 출력할 떄 나타날 값
        return self.pet_name

class Pet_diet_set(models.Model):
    pet_name = models.ForeignKey(Pet_info, on_delete = models.CASCADE)
    pet_weight = models.DecimalField(decimal_places=2, max_digits = 100)
    pet_feed_Kcal = models.IntegerField()
    pet_status = models.CharField(max_length=100, choices = pet_status_choices ,verbose_name="반려견 상태")
    
    pet_feed_time_B = models.TimeField()
    pet_feed_time_L = models.TimeField()
    pet_feed_time_D = models.TimeField(null=True, blank = True)
    
    pet_needKcal = models.IntegerField(verbose_name="하루 필요 칼로리")
    pet_feed_amount = models.IntegerField(verbose_name="사료 총량")
    pet_standard_feed = models.IntegerField(verbose_name='기준 급식량', null = True)

class Pet_daily_feeding(models.Model):
    pet_name = models.ForeignKey(Pet_info, on_delete = models.CASCADE)

    feed_date = models.DateField(verbose_name = "날짜")
    feed_time = models.TimeField(verbose_name = "급여 시간")
    feed_amount = models.IntegerField(verbose_name = '급여된 사료량')
    remain_amount = models.IntegerField(verbose_name = "남은 사료량", null = True)
    feed_index = models.BooleanField(default=False)

    def __str__(self):
    # 객체를 출력할 떄 나타날 값
        return f"{self.feed_date} - {self.pet_name}"    

App_Main/forms.py
from django import forms
from .models import *

class PetForm(forms.ModelForm):
    pet_name = forms.CharField(error_messages={'required':'반려견의 이름을 입력해주세요!'}, label='반려견 이름')
    
    class Meta:
        model = Pet_info  # 사용할 모델
        fields = ['pet_name', 'pet_birth']

class PetdietForm(forms.ModelForm):
    pet_feed_Kcal = forms.IntegerField(label='사료 칼로리')
    pet_status = forms.ChoiceField(choices = pet_status_choices, label='반려견 상태')
    pet_weight = forms.CharField(label='체중')

    pet_feed_time_B = forms.TimeField(label='첫 번째 급여')
    pet_feed_time_L = forms.TimeField(label='두 번째 급여')


    class Meta:
        model = Pet_diet_set
        fields = ['pet_feed_Kcal','pet_status', 'pet_weight','pet_feed_time_B','pet_feed_time_L','pet_feed_time_D',]


App_Main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from . models import *
from . forms import *
from . Calcul import DER
# 함수형 뷰에서 사용하는 권한 제한
from django.contrib.auth.decorators import login_required
import json

def Main_Home(request):
    if request.method == 'POST' and request.POST['feed_amount']:
        feed_amount = {'feed_amount':request.POST['feed_amount']}
        with open('Feed_Amount.json', 'w', encoding="utf-8") as make_file:
            json.dump(feed_amount, make_file)
        

    return render(request, 'Main_Home.html')
def Pet_info_View(request):
    try:
        Pet = Pet_info.objects.get(pet_owner=request.user)
    except:
        Pet = None
   
    try:
        Pet_diet_info = get_object_or_404(Pet_diet_set, pet_name = Pet)
    except:
        Pet_diet_info = None

    context = {'Pet' : Pet, 'Pet_diet_info' : Pet_diet_info}

    if request.path == '/pet/info':
        return render(request, 'Pet_info.html',context)
    elif request.path == '/pet/diet/info':
        return render(request, 'Pet_diet_info.html',context)
    
@login_required(login_url='App_User:login')
def Pet_create_View(request):
    if request.method == 'POST':
        form = PetForm(request.POST)
        if form.is_valid():
            Pet_info = form.save(commit=False)
            Pet_info.pet_owner = request.user
            Pet_info.save()   
            return redirect("App_Main:pet")
    else:
        form = PetForm() # -> unboundForm

    return render(request, 'Pet_create.html',{'form': form})
  
@login_required(login_url='App_User:login')
def Pet_update_View(request):
    pet_info = get_object_or_404(Pet_info, pet_owner = request.user)
    
    if request.method == 'POST':
        print(request)
        form = PetForm(request.POST, instance = pet_info)
        if form.is_valid():
            Pet = form.save(commit=False)
            Pet.pet_owner = request.user
            Pet.save()   
            return redirect("App_Main:pet")
    else:
        form = PetForm(instance = pet_info) # -> unboundForm
    context = {'form': form, 'pet_info' : pet_info}
    return render(request, 'Pet_create.html',context)

@login_required(login_url='App_User:login')
def Pet_statistics_View(request):
    try:
        pet_info = get_object_or_404(Pet_info, pet_owner = request.user)
    except:
        messages.error(request, '변려견을 먼저 등록해주세요!')
        return redirect("App_Main:pet_diet_info")
    try:
        pet_diet_info = get_object_or_404(Pet_diet_set, pet_name = pet_info )
    except:
        messages.error(request, '반려견의 식단 정보를 설정해주세요.')
        return redirect("App_Main:pet_diet_info")
#Pet_daily_feeding
    content = {'pet_diet_info':pet_diet_info,}
    return render(request, 'Pet_statistics.html', content)

@login_required(login_url='App_User:login')
def Pet_diet_set_View(request):
    try:
        pet_info = get_object_or_404(Pet_info, pet_owner = request.user)
    except:
        messages.error(request, '변려견을 먼저 등록해주세요!')
        return redirect("App_Main:pet_diet_info")
    if request.path == '/pet/diet/update':
        pet_diet_info = get_object_or_404(Pet_diet_set, pet_name = pet_info )
    else:
        pet_diet_info = None

    if request.method == 'POST':
        form = PetdietForm(request.POST, instance = pet_diet_info)
        if form.is_valid():
            Der = DER(float(request.POST['pet_weight']), request.POST['pet_status'])
            pet_diet_info = form.save(commit=False)
            pet_diet_info.pet_name = pet_info
            pet_diet_info.pet_needKcal = int(Der)
            pet_diet_info.pet_feed_amount = round(Der / int(request.POST['pet_feed_Kcal']) * 100)
            pet_diet_info.save()
            return redirect("App_Main:pet_diet_info")
    else:
        form = PetdietForm(instance = pet_diet_info) # -> unboundForm
    context = {'pet_diet_set':pet_diet_info,'pet_info' : pet_info, 'form': form,'pet_status_choices':pet_status_choices}
    return render(request, 'Pet_diet_set.html', context)

App_Main/templates/Main_Home.html
{% extends "base.html" %}
{% block content %}
<div class="container" width="10px">
    <h1 class="mt-4">정보통신공학과</h1>
    <h2>스마트 자동 급여기</h2>
    {% if user.is_authenticated %} 
    <p>당신의 반려견을 위한 스마트 자동 급여기를 소개합니다. </p>
    <p>이 기기는 사용자가 저희가 제공하는 웹사이트에 입력한 정보를 기반으로 정해진 시간에 적정량의 사료를 자동으로 공급해 줍니다.</p>
    <p>이를 위해 무게 센서와 모터를 사용하여 추출 메커니즘과 웹 서버와의 실시간 통신을 라즈베리파이를 통해 구현하였습니다.</p>
    <p>이 스마트 자동 급여기를 사용하면 바쁜 일상에서도 반려견의 식사 챙김에 대한 걱정과 올바른 식사 습관 형성에 도움을 줄 수 있습니다.</p>
    {% else %}
    <p>우측 상단에서 회원가입 또는 로그인을 진행해주세요.</p>
    {% endif %}
</div>
{% endblock %}

App_Main/templates/Pet_create.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="pet_name">반려견 이름</label>
                    <input type="text" class="form-control" name="pet_name" id="pet_name"
                    placeholder="" value="{{ pet_info.pet_name }}">
                </div>
                <div class="mb-3">
                    <label for="pet_birth">생일[생략 가능]</label>
                    <input type="date" class="form-control" name="pet_birth" id="pet_birth"
                     value="{{ pet_info.pet_birth }}">
                </div>
                <button type="submit" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">반려 동물 등록</button>
            </form>
        </div>
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>      
</div>
{% endblock %}

App_Main/templates/Pet_diet_info.html
{% extends "base.html" %}
{% block content %}
<h5 class="border-bottom pb-2 mb-3">설정 페이지</h5>
<div class="content_block">
    <div class="table-responsive">
        {% if Pet_diet_info %}
        <table class="table table-sm table-hover" width = '10%'>
            <tbody class="text-center">
                <tr>
                    <th class="align-middle" scope="col">반려견 이름</th>                            
                    <td>{{ Pet_diet_info.pet_name }}</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">반려견 몸무게</th>                        
                    <td step='0.01' >{{ Pet_diet_info.pet_weight }}KG</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">반려견 상태</th>                        
                    <td>{{ Pet_diet_info.pet_status }}</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">첫 번째 급여</th>                        
                    <td>{{ Pet_diet_info.pet_feed_time_B }}</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">두 번째 급여</th>                        
                    <td>{{ Pet_diet_info.pet_feed_time_L }}</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">세 번째 급여</th>                        
                    <td>{{ Pet_diet_info.pet_feed_time_D|default:'생략' }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{% url 'App_Main:pet_diet_update' %}" class="btn btn-sm text-light bg-dark" ">반려견 식단 정보 수정</a>
        <table class="table table-sm table-hover" width = '10%'>
            <tbody class="text-center">
                <tr>
                    <th class="align-middle" scope="col">반려견 하루 필요 칼로리</th>                  
                    <td>{{ Pet_diet_info.pet_needKcal }}Kcal</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">반려견 사료 칼로리</th>                  
                    <td>{{ Pet_diet_info.pet_feed_Kcal }}Kcal(100g)</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">하루 지급 사료 총량</th>                        
                    <td>{{ Pet_diet_info.pet_feed_amount }}g</td>
                </tr>
            </tbody>
        </table>

        
        {% else %}
        <h4> 등록된 식단 정보가 없습니다. 새로 등록해 주세요.</h4>
        <a href="{% url 'App_Main:pet_diet_set' %}" class="btn btn-sm text-light bg-dark" ">반려견 식단 정보 등록</a>
        {% endif %}
        
        
        

        {% if messages %}
        {% for message in messages %}
            <div class="row" style="margin:20px auto;">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                <strong>{{ message.tags }}!</strong> {{ message.message }}
                </div>
            </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>  
</div>
{% endblock %}

App_Main/templates/Pet_diet_set.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="pet_weight">반려견 체중</label>
                    <input type="number" step="0.01" class="form-control" name="pet_weight" id="pet_weight" placeholder="KG 단위로 입력해주세요." value="{{ pet_diet_set.pet_weight }}">
                </div>
                <div class="mb-3">
                    <label for="pet_feed_Kcal">사료 정보</label>
                    <a href="https://tools.mypetlife.co.kr/food-calorie">참조 사이트</a>
                    <input type="number" class="form-control" name="pet_feed_Kcal" id="pet_feed_Kcal"
                    placeholder="100g당 Kcal단위로 숫자만 입력해주세요." value="{{ pet_diet_set.pet_feed_Kcal }}">
                    
                </div>
                <div class="mb-3">
                    <label for="pet_status" >반려견 상태</label>
                    <select name="pet_status" class="form-control" id="pet_status">
                        {% for i,j in pet_status_choices%}
                            {% if i == pet_diet_set.pet_status %}
                            <option value="{{ i }}" selected>{{i}}</option>
                            {% else %}
                            <option value="{{ i }}">{{i}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>                    
                </div>

                <div class="mb-3">
                    <label for="pet_feed_time_B">첫 번째 급여 시간[필수]</label>
                    <input type="time" class="form-control" name="pet_feed_time_B" id="pet_feed_time_B" value="{{ pet_diet_set.pet_feed_time_B|time:'H:i' }}">
                </div>
                <div class="mb-3">
                    <label for="pet_feed_time_L">두 번째 급여 시간[필수]</label>
                    <input type="time" class="form-control" name="pet_feed_time_L" id="pet_feed_time_L" value="{{ pet_diet_set.pet_feed_time_L|time:'H:i' }}">
                </div>
                <div class="mb-3">
                    <label for="pet_feed_time_D">세 번째 급여 시간[생략 가능]</label>
                    <input type="time" class="form-control" name="pet_feed_time_D" id="pet_feed_time_D" value="{{ pet_diet_set.pet_feed_time_D|time:'H:i' }}">
                </div>                
                <button type="submit" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">식단 정보 등록</button>
            </form>
        </div>
       
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>      
</div>
{% endblock %}

App_Main/templates/Pet_info.html
{% extends "base.html" %}
{% block content %}
<h5 class="border-bottom pb-2 mb-3">반려견 페이지</h5>
<div class="content_block">
    <div class="table-responsive">
        {% if Pet %}
        <table class="table table-sm table-hover" width = '10%'>
            <tbody class="text-center">
                <tr>
                    <th class="align-middle" scope="col">반려견 이름</th>                            
                    <td>{{ Pet.pet_name }}</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">반려견 생일</th>                     
                    <td>{{ Pet.pet_birth|default:'생일이 등록되지 않았습니다.' }}</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">반려견 몸무게</th>                        
                    <td step='0.01' >{{ Pet_diet_info.pet_weight|default:'--' }}KG</td>
                </tr>
                <tr>
                    <th class="align-middle" scope="col">반려견 상태</th>                        
                    <td>{{ Pet_diet_info.pet_status|default:'식단 설정을 해주세요.'  }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{% url 'App_Main:pet_update' %}" class="btn btn-sm text-light bg-dark" ">반려견 정보 수정</a>
            {% if not Pet_diet_info %}
            <div class="alert alert-danger">설정 카테고리에서 식단 설정을 해주세요.</div>                
            {% else %}
            <tr>
                <a href="{% url 'App_Main:pet_diet_info' %}" class="btn btn-sm text-light bg-dark" ">반려견 식단 정보 보기</a>
            </tr>
            {% endif %}
        {% else %}
        <h4> 등록된 반려견이 없습니다. 새로 등록해 주세요.</h4>
        <a href="{% url 'App_Main:pet_create' %}" class="btn btn-sm text-light bg-dark" ">반려견 정보 등록</a>
        {% endif %}

        {% if messages %}
        {% for message in messages %}
            <div class="row" style="margin:20px auto;">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                <strong>{{ message.tags }}!</strong> {{ message.message }}
                </div>
            </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>  
</div>
{% endblock %}

App_Main/templates/Pet_statistics.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/calender.css' %}">
<div class="calendar">
    <div class="calendar_header">
        <div class="calendar_nav">
            <button class="nav-btn go-prev">&lt;</button>
            
            <span class="year"></span>년
            <span class="month"></span>월

            <button class="nav-btn go-next">&gt;</button>
            <button class="nav-btn go-today" style="font-weight: 900;">Today</button>
        </div>
    </div>
    <div class="calendar_main">
        <div class="days">
            <div class="day">일</div>
            <div class="day">월</div>
            <div class="day">화</div>
            <div class="day">수</div>
            <div class="day">목</div>
            <div class="day">금</div>
            <div class="day">토</div>
        </div>
        <div class="dates"></div>
    </div>

    <!-- 상세창 -->
    <div class="resv-wrapper" style="display: none;">
        <div class="resv-bg">
            <button class="resv-close">X</button>
            <div class="resv_info">
                <div class="resv_ym" style="text-align: center ">
                    <h3>
                        <span class="Select_year"></span>년
                        <span class="Select_month"></span>월
                        <span class="Select_dates"></span>일의 급여 기록
                    </h3>
                    <p class="feedings">
                        <br>
                    </p>
                </div>    
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/calender.js' %}"></script>
<script src="{% static 'js/reserve.js' %}"></script>
{% endblock %}

App_Main/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
        {% if field.errors %}
        <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        </div>
        {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}