App_Main/urls.py
from django.urls import path
from .views import *
app_name='App_Main'

urlpatterns = [
    path('', Main_Home, name = 'home'),
    path('pet/info',Pet_info_View, name = 'pet'),  
    path('pet/info/create', Pet_create_View, name = 'pet_create'),
    path('pet/info/update', Pet_update_View, name  = 'pet_update'),
    path('pet/statistics', Pet_statistics_View, name = 'pet_statistics'),
    path('pet/diet/info', Pet_info_View, name = 'pet_diet_info'),
    path('pet/diet/set', Pet_diet_set_View, name = 'pet_diet_set'),
    path('pet/diet/update', Pet_diet_set_View, name = 'pet_diet_update'),
]


App_User/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
app_name = "App_User"

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup_view, name='signup'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views as TokenViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Main.urls')),
    path('auth/', include('App_User.urls')),
    path('wsc/', include('App_WSC.urls')),
    path('api/', include('App_API.urls')),
    path("api/auth", TokenViews.obtain_auth_token, name="obtain_auth_token"),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>졸작 프로젝트 페이지</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<body>
<!-- 네비게이터 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <table width="100%">
            <tr>
                <td width="5%">
                    <a class="navbar-brand" href="/">캡스톤</a>
                </td>
                <td class='custom_td' width="50%"></td>
                <td width="10%">
                    <div class="nav navbar-nav ml-auto">
                        
                            {% if user.is_authenticated %}  
                            <a class="nav-link" href="/admin"><i class="fas fa-user-plus"></i>{{ user }}</a>
                            <a class="nav-link" href="{% url 'App_User:logout' %}">Logout</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'App_User:signup' %}"><i class="fas fa-user-plus"></i> Sign</a>
                            <a class="nav-link" href="{% url 'App_User:login' %}">Login</a>
                            {% endif %}
                     
                    </div>
                </td>
            </tr>
        </table>
    </div>
</nav>
    <div class = "container mt-3">
        <div class = "row">
            <div class="col-sm-12 col-md-3 col-lg-2 p-2">
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/">Home</a>
                    {% if user.is_authenticated %} 
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'App_Main:pet' %}">반려견</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'App_Main:pet_statistics' %}">통계</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'App_Main:pet_diet_info' %}">설정</a>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-10 p-2">
                {% block content %}

                {% endblock %}

                {% block pagination %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>